#!/usr/bin/env ruby per https://learn.co/tracks/bootcamp-prep/ruby-fundamentals/command-line-applications/cli-applications-in-ruby 
# ruby bin/< your file name >
# $ chmod +x <file_name>

#Create an Exhibit (what artist, what museum - list them all?)
#Purchase a Work (by which artist? create new artist and painting? from painting class Artist.new)
#Update Records 
#Delete Records eg Destroy a Work, sell a work  
#End Exhibit (?)
#Retrieve Information about exhibits, artistis, paintings 
